In [1]:
import pandas as pd                     # работа с табличными данными
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
import seaborn as sns
import os
from io import StringIO, BytesIO
import joblib

# import boto3
# import mlflow
# import mlflow.sklearn

# print(pd.__version__)

In [24]:
df = pd.read_csv('../data/input_data/car data.csv')
df.head(10)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
5,vitara brezza,2018,9.25,9.83,2071,Diesel,Dealer,Manual,0
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,0
7,s cross,2015,6.50,8.61,33429,Diesel,Dealer,Manual,0
8,ciaz,2016,8.75,8.89,20273,Diesel,Dealer,Manual,0
9,ciaz,2015,7.45,8.92,42367,Diesel,Dealer,Manual,0

In [29]:
df_clean = df.copy()

In [30]:
df_clean.head(10)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
5,vitara brezza,2018,9.25,9.83,2071,Diesel,Dealer,Manual,0
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,0
7,s cross,2015,6.50,8.61,33429,Diesel,Dealer,Manual,0
8,ciaz,2016,8.75,8.89,20273,Diesel,Dealer,Manual,0
9,ciaz,2015,7.45,8.92,42367,Diesel,Dealer,Manual,0

In [23]:
initial_count = len(df_clean)
df_clean = df_clean.dropna(subset=['Selling_Price'])
df_clean.head(10)

Empty DataFrame
Columns: [Car_Name, Year, Selling_Price, Present_Price, Kms_Driven, Fuel_Type, Seller_Type, Transmission, Owner]
Index: []

In [42]:
df_clean['Year'] = df_clean['Year'].astype(int)
df_clean['Kms_Driven'] = df_clean['Kms_Driven'].astype(int)

df_clean.head(10)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Car_Age,Kms_Per_Year
14,dzire,2009,2.25,7.21,77427,Petrol,Dealer,Manual,0,1,38713.500000
19,sx4,2010,2.65,7.98,41442,Petrol,Dealer,Manual,0,0,41442.000000
28,alto k10,2010,1.95,3.95,44542,Petrol,Dealer,Manual,0,0,44542.000000
39,sx4,2003,2.25,7.98,62000,Petrol,Dealer,Manual,0,7,7750.000000
42,sx4,2008,1.95,7.15,58000,Petrol,Dealer,Manual,0,2,19333.333333
47,wagon r,2006,1.05,4.15,65000,Petrol,Dealer,Manual,0,4,13000.000000
54,innova,2005,2.75,10.21,90000,Petrol,Individual,Manual,0,5,15000.000000
55,corolla altis,2009,3.60,15.04,70000,Petrol,Dealer,Automatic,0,1,35000.000000
57,corolla altis,2010,4.75,18.54,50000,Petrol,Dealer,Manual,0,0,50000.000000
67,fortuner,2010,9.25,20.45,59000,Diesel,Dealer,Manual,0,0,59000.000000