In [1]:
import pandas as pd
import pyarrow as pa
print(pd.__version__)
print(pa.__version__)

2.3.2
21.0.0

In [2]:
df_prq = pd.read_parquet('../data/output_data/car_data_cleaned.parquet')
df_prq.head(10)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Car_Age,Kms_Per_Year
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0,11,2250.000000
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0,12,3307.692308
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0,8,766.666667
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0,14,346.666667
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0,11,3537.500000
5,vitara brezza,2018,9.25,9.83,2071,Diesel,Dealer,Manual,0,7,258.875000
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,0,10,1708.727273
7,s cross,2015,6.50,8.61,33429,Diesel,Dealer,Manual,0,10,3039.000000

In [5]:
df_prq_s3 = pd.read_parquet('../data/output_data/part-00000-03df2316-ffcb-44b7-8018-afb9a13d66f7-c000.snappy.parquet')
df_prq_s3.head(20)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Car_Age,Kms_Per_Year
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0,11,2454.545455
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0,12,3583.333333
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0,8,862.500000
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0,14,371.428571
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0,11,3859.090909
5,vitara brezza,2018,9.25,9.83,2071,Diesel,Dealer,Manual,0,7,295.857143
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,0,10,1879.600000
7,s cross,2015,6.50,8.61,33429,Diesel,Dealer,Manual,0,10,3342.900000
8,ciaz,2016,8.75,8.89,20273,Diesel,Dealer,Manual,0,9,2252.555556
9,ciaz,2015,7.45,8.92,42367,Diesel,Dealer,Manual,0,10,4236.700000
10,alto 800,2017,2.85,3.60,2135,Petrol,Dealer,Manual,0,8,266.875000
11,ciaz,2015,6.85,10.38,51000,Diesel,Dealer,Manual,0,10,5100.000000
12,ciaz,2015,7.50,9.94,15000,Petrol,Dealer,Automatic,0,10,1500.000000
13,ertiga,2015,6.10,7.71,26000,Petrol,Dealer,Manual,0,10,2600.000000
14,dzire,2009,2.25,7.21,77427,Petrol,Dealer,Manual,0,16,4839.187500
15,ertiga,2016,7.75,10.79,43000,Diesel,Dealer,Manual,0,9,4777.777778
16,ertiga,2015,7.25,10.79,41678,Diesel,Dealer,Manual,0,10,4167.800000
17,ertiga,2016,7.75,10.79,43000,Diesel,Dealer,Manual,0,9,4777.777778
18,wagon r,2015,3.25,5.09,35500,CNG,Dealer,Manual,0,10,3550.000000
19,sx4,2010,2.65,7.98,41442,Petrol,Dealer,Manual,0,15,2762.800000